export const files: any = [
    {
        dirName:"channel",
        files:[
            "ar-tg-mastering",
            "channev",
            "cS3301",
            "cS5501",
            "dd-channel",
            "dd-channel2",
            "hq2",
            "loaded",
            "sslgchannel",
        ]
    },
    {
        dirName:"comp",
        files:[
            "britpressor",
            "bx_masterdesk Classic",
            "bx_opto",
            "cla-76",
            "couture",
            "DD Expander",
            "DD Gate",
            "DD Limiter",
            "dd-compressor",
            "dd-deesser",
            "dynaridemono",
            "free87-fr-comp",
            "Leveling Tool",
            "Limited-Z_v2",
            "MaxxVolume",
            "MJUCjr",
            "OTT",
            "PolyComp",
            "ReaComp",
            "ReaLimit",
            "ReaXcomp",
            "RoughRider3",
            "SPECOMP",
            "Supercharger",
            "TDR Kotelnikov",
            "TDR Nova",
            "W1 Limiter"
        ]
    },
    {
        dirName:"EQ Linear",
        files:[
            "ReaEQ"
        ]
    },
    {
        dirName:"EQ non Linear",
        files:[
            "BaxterEQ",
            "BootEQmkII",
            "BritChannel",
            "BritPre",
            "bx_cleansweep V2",
            "bx_subfilter",
            "DD AutoFilter",
            "DD DJEQ",
            "DD DualFilter",
            "DD Equaliser",
            "DD Filter",
            "elysia niveau filter",
            "Kramer HLS",
            "Maag EQ2",
            "PTEq-X",
            "ReaDelay",
            "SGA1566",
            "SonEQ",
            "TDR VOS SlickEQ",
            "VHL-3C",
            "XCTR v2",
            "XCTR",
        ]
    },
    {
        dirName:"FX",
        files:[
            "Amped - Stevie T",
            "BC Flanger 3",
            "Blacksun",
            "BOD",
            "bx_rockrack V3",
            "bx_solo",
            "CamelCrusher",
            "Canary",
            "Cassette Transport",
            "ChorusWS1",
            "Classic Flanger",
            "Cypress TT-15",
            "DD AutoPan",
            "DD BitCrusher",
            "DD Chorus",
            "DD Delay",
            "DD Flanger",
            "DD MonoDelay",
            "DD Overdrive",
            "DD Phaser",
            "DD Reverb",
            "DD RingMod",
            "DD SigGen",
            "DD TiltEQ",
            "DD Tremolo",
            "DD Utility",
            "Distox",
            "FetDrive",
            "FetSnap",
            "Focus",
            "GK Amplification 3 LE",
            "Glitch",
            "Grind Machine",
            "GSatPlus",
            "HeadCrusherFREE",
            "Hellbeast v2",
            "Ignite - Emissary",
            "Ignite - NadIR",
            "IVGI2",
            "La Petite Excite",
            "lawnmower1.3",
            "Lazy Kenneth",
            "Lofi Space",
            "MetaFilter",
            "MIKKO2",
            "Movement",
            "Nebula",
            "Oracle",
            "Ozone Imager 2",
            "PhreePhuzz",
            "ReaFir",
            "ReaPitch",
            "ReaSurround",
            "ReaSurroundPan",
            "ReaVerb",
            "ReaVerbate",
            "ReaVoice",
            "Replika",
            "RX 8 De-click",
            "RX 8 De-clip",
            "RX 8 Voice De-noise",
            "Saturation Knob",
            "Schoeps Double MS",
            "Screamer",
            "SDRR2tube",
            "Sound Delay",
            "SPAN",
            "SPL Attacker Plus",
            "The Punch",
            "TONEX",
            "Tube Amp",
            "Vinyl",
        ]
    },
]